### ISSUE TITLE
DB password

### ISSUE THREAD

**Issue by gokkstudio** [ShubhamBansal1997/Business_Directroy_Listing_System#1]
hi, what is default admin password?
Thanks

**Comment by ShubhamBansal1997** [comment]
Password - admin

[https://github.com/ShubhamBansal1997/Business_Directroy_Listing_System/blob/50f655224f74a163e77b40323773fc87f8fd12c0/database/seeds/UsersTableSeeder.php#L24](https://github.com/ShubhamBansal1997/Business_Directroy_Listing_System/blob/50f655224f74a163e77b40323773fc87f8fd12c0/database/seeds/UsersTableSeeder.php#L24)
If you are working or using this. Please feel free to contribute towards the code and documentation.

**Comment by gokkstudio** [comment]
Thanks man, I just installed and will check it out - looks really good
